//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EorzeanFisher.Ressources.Text {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_fr_FR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EorzeanFisher.Ressources.Text.Localization_fr-FR", typeof(Localization_fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sastasha.
        /// </summary>
        internal static string DUNGEON_01 {
            get {
                return ResourceManager.GetString("DUNGEON_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Hypogée de Tam-Tara.
        /// </summary>
        internal static string DUNGEON_02 {
            get {
                return ResourceManager.GetString("DUNGEON_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Donjons.
        /// </summary>
        internal static string ITEM_GUIDE_01 {
            get {
                return ResourceManager.GetString("ITEM_GUIDE_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Défis.
        /// </summary>
        internal static string ITEM_GUIDE_02 {
            get {
                return ResourceManager.GetString("ITEM_GUIDE_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Donjons.
        /// </summary>
        internal static string TITLE_GUIDE_DUNGEON_LIST {
            get {
                return ResourceManager.GetString("TITLE_GUIDE_DUNGEON_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lore.
        /// </summary>
        internal static string TITLE_GUIDE_DUNGEON_LORE {
            get {
                return ResourceManager.GetString("TITLE_GUIDE_DUNGEON_LORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stratégie.
        /// </summary>
        internal static string TITLE_GUIDE_DUNGEON_STRAT {
            get {
                return ResourceManager.GetString("TITLE_GUIDE_DUNGEON_STRAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résumé.
        /// </summary>
        internal static string TITLE_GUIDE_DUNGEON_SUMMARY {
            get {
                return ResourceManager.GetString("TITLE_GUIDE_DUNGEON_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Récompenses.
        /// </summary>
        internal static string TITLE_GUIDE_DUNGEON_TREASURE {
            get {
                return ResourceManager.GetString("TITLE_GUIDE_DUNGEON_TREASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Guides.
        /// </summary>
        internal static string TITLE_GUIDE_LIST {
            get {
                return ResourceManager.GetString("TITLE_GUIDE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coffre de Boss 1.
        /// </summary>
        internal static string TITLE_TREA_SASTASHA_01 {
            get {
                return ResourceManager.GetString("TITLE_TREA_SASTASHA_01", resourceCulture);
            }
        }
    }
}
